# 静态文件任务相关配置
[static]
    [static.ssh]
        ip = "192.168.18.44"
        port = "22"
        user = "root"
        pass = "1q2w3e4r"
    [static.dir]
        # 远程目录
        remoteDir = "/zhq/Medias"
        # 本地备份目录
        localBakDir = "D:\\Workspace\\golang\\src\\inotify_produce\\file\\static"
        # 存放目标目录
        targetDir = "\\\\191.191.191.174\\data2021"
#        targetDir = "D:\\tag"
        # 失败拷贝目录
        failDir = "D:\\Workspace\\golang\\src\\inotify_produce\\file\\fail\\static"
# mysql binlog文件生产配置
[mysql]
    # redis配置
    [mysql.redis]
        ip = "192.168.18.44"
        port = 6379
        pass = "1q2w3e4r"
        db = 0
    # 文件存储相关配置
    [mysql.dir]
        # 文件切分偏移量
        rowSize = 10000
        # 目标目录
        targetDir = "\\\\191.191.191.174\\data2021"
#        targetDir = "D:\\tag"
        # 本地备份目录
        localBakDir = "D:\\Workspace\\golang\\src\\inotify_produce\\file\\binlog"
        # 失败拷贝目录
        failDir = "D:\\Workspace\\golang\\src\\inotify_produce\\file\\fail\\binlog"
# 压缩包密码配置
[zip]
    password = "fwYD$RFV&^%$9umh"


